# Entry error
CONVERT_DATA_ERROR = 101

# Prepare task error
TASK_PREPARE_DATA_ERROR = 201
INPUT_FILE_EXTENSION_ERROR = 202
TASK_CONVERT_SCHEMA_ERROR = 203
TASK_CONVERT_DATA_ERROR = 204

# Download & cache error
CREATE_TEMP_DIR_ERROR = 301
DOWNLOAD_CKAN_RESOURCE_ERROR = 302

# MYSQL error
MYSQL_DATABASE_CONNECTION_ERROR = 401
MYSQL_UNSPECIFIED_DATABASE_ERROR = 402
MYSQL_EXPORT_SCHEMA_ERROR = 403
MYSQL_RESTORE_DATA_ERROR = 404
MYSQL_FETCH_DATA_TO_MONGO_ERROR = 405
MYSQL_CREATE_DATABASE_ERROR = 406
MYSQL_DATABASE_NOT_FOUND_ERROR = 407

# Mongo error
MONGO_DATABASE_CONNECTION_ERROR = 451
MONGO_UNSPECIFIED_DATABASE_ERROR = 452
MONGO_DROP_DATABASE_ERROR = 453
MONGO_IMPORT_SCHEMA_ERROR = 454
MONGO_CREATE_SCHEMA_VIEW_ERROR = 455
MONGO_DROP_COLLECTION_ERROR = 456
MONGO_STORE_DATA_TO_COLLECTION_ERROR = 457
MONGO_COLLECTION_NOT_FOUND = 458
