# Entry error
CONVERT_DATA_ERROR = 101

# Prepare task error
TASK_PREPARE_DATA_ERROR = 201
INPUT_FILE_EXTENSION_ERROR = 202

# Download & cache error
CREATE_TEMP_DIR_ERROR = 301
DOWNLOAD_CKAN_RESOURCE_ERROR = 302

# MYSQL error
MYSQL_DATABASE_CONNECTION_ERROR = 401
MYSQL_UNSPECIFIED_DATABASE_ERROR = 402
MYSQL_EXPORT_SCHEMA_ERROR = 405

# Mongo error
MONGO_DATABASE_CONNECTION_ERROR = 404
MONGO_UNSPECIFIED_DATABASE_ERROR = 403
MONGO_DROP_DATABASE_ERROR = 406
